name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/*.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Retrieve version
        run: |
          version=`awk -F "=" '$1 == "version" {print $2}' gradle.properties`
          commit_count=`git rev-list HEAD --count`
          version="${version}.r${commit_count}"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build with gradle
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew --no-daemon -Dorg.gradle.jvmargs=-Xmx2g -Pversion=$VERSION dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: BiliRoamingX-${{ env.VERSION }}
          path: 'build'

       - create-release:
    needs: build
    if: github.ref_type == 'tag'  # 仅当推送 tag 时触发
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "非官方构建 ${{ github.ref_name }}"
          body: |
            ⚠️ 警告：此为非官方构建版本
            ----------------------------
            - 构建日期: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            - 提交哈希: ${{ github.sha }}
            - 原项目: [BiliRoamingX](${{ github.repository }})
          files: |
            *.apk
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用你的 TOKEN
